name: Deploy WebJob

on:
  workflow_dispatch:
  
  push:
    branches: [ tgbot-story-telling ]

env:
  AZURE_WEBAPP_NAME: story-telling-tgbot    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
      - name: Prepare .env file with project settings
        
        run: echo "BOT_TOKEN=${{secrets.BOT_TOKEN}}" >> ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp/.env |
            echo "OPEN_AI_TOKEN=${{secrets.OPEN_AI_TOKEN}}" >> ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp/.env
        
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_TGBOT  }} 
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'