name: Deploy WebJob

on:
  workflow_dispatch:
  
  push:
    branches: [ develop ]

env:
  WEBJOB_NAME: TgBotConsoleApp
  AZURE_APP_NAME: story-telling-tgbot
  DOTNET_VERSION: '8.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repo  
      - uses: actions/checkout@v2
      
      # Setup .NET Core SDK  
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet test
        run: |
          dotnet build --configuration Release      
      
      - name: dotnet publish
        run: |
          dotnet publish -c Release -o './publish/App_Data/Jobs/Triggered/${{ env.WEBJOB_NAME }}'

      - name: Prepare .env file with project settings
        run: echo "BOT_TOKEN=${{secrets.BOT_TOKEN}}" >> .env |
            echo "OPEN_AI_TOKEN=${{secrets.OPEN_AI_TOKEN}}" >> .env
          
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_TGBOT }}
          package: './publish'  